### ISSUE TITLE
[bug] can't open other's resume and see comment

### ISSUE THREAD

**Issue by suhuboice** [levys19/Cracking_the_resume#140]
For the url provided for alpha release, nothing happened when I click on others' resume when I logged in and click view other resumes. This function was showed in the youtube video (which was running on the local machine) but it cannot perform on the url provided.
<img width="998" alt="2018-03-29 4 41 13" src="https://user-images.githubusercontent.com/36173625/38112532-3b0d6128-3370-11e8-8328-0287bec796e1.png">

**Comment by Sravanika** [comment]
Thank you for reporting the bug
