### ISSUE TITLE
[Critical bug] Cannot sign up

### ISSUE THREAD

**Issue by zhaosec** [levys19/Cracking_the_resume#236]
I was unable to sign up.  If I choose doc file, then I have to select pdf in order to sign up, but I can't click on that as well. 
![screenshot 8](https://user-images.githubusercontent.com/20166737/38774732-8bff3cf8-403d-11e8-969a-c3d8ed4d49c9.png)

**Comment by lieselva** [comment]
Our web app only accepts PDFs.  We specified it right below the upload button ("Choose File") in bold. Sorry for the inconvenience.

**Comment by zhaosec** [comment]
I choose Resume.docx as my resume to submit. But I can't proceed in any manner.

**Comment by lieselva** [comment]
A .docx file is not the same as a .pdf file. Please convert your .docx file to a .pdf file on your computer and try again.

**Comment by zhaosec** [comment]
Oh...Yeah, I misread it sorry about that.
