### ISSUE TITLE
Bug: Keeps showing me Username Not Found

### ISSUE THREAD

**Issue by Manvijay** [levys19/Cracking_the_resume#248]
After successfully registering on the web app, when I am trying to log in it shows "User Not Found".

**Comment by Sravanika** [comment]
Could you give us more details about this error? Did you try uploading a resume that's more than one page?

**Comment by Manvijay** [comment]
I went to the link provided in the ReadMe and registered myself by using a dummy email address (i.e bvv@b). It showed that I have successfully registered but when I tried logging in, it kept on showing that user not found. Then I tried registering with a valid email address (my buffalo email id), even then I got the exact same result.

**Comment by Sravanika** [comment]
Is your resume more than one page? I can still sign up.

**Comment by lieselva** [comment]
I think the problem is you are trying to log in with your email address. You would have to log in with the username that you created along with your password. If you continue to have problems, please let us know.
