### ISSUE TITLE
[Trivial Bug] Not able to use the username box

### ISSUE THREAD

**Issue by arturoto** [levys19/Cracking_the_resume#251]
At a certain aspect ratio the text does not allow access to the username box.
Browser: Firefox 59.0.1
OS: MacOS 10.12.6

<img width="936" alt="screen shot 2018-04-20 at 12 26 27 pm" src="https://user-images.githubusercontent.com/16159696/39062993-75b79824-4497-11e8-8163-24fbb441f4fb.png">

**Comment by lieselva** [comment]
Thanks for reporting the bug.
